COMMON: &common
  SECRET_KEY: insecure
  DEBUG: False

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF