import turtle

turtle.color("blue")
turtle.circle(100)

turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.color("green")
turtle.circle(100)

turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.color("black")
turtle.circle(100)

turtle.penup()
turtle.goto(100,-200)
turtle.pendown()
turtle.color("green")
turtle.circle(100)

turtle.penup()
turtle.goto(-100,-200)
turtle.pendown()
turtle.color("green")
turtle.circle(100)
#######################################
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.color("blue")
turtle.circle(50)

turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.color("green")
turtle.circle(50)

turtle.penup()
turtle.goto(100,0)
turtle.pendown()
turtle.color("black")
turtle.circle(50)

turtle.penup()
turtle.goto(50,-100)
turtle.pendown()
turtle.color("green")
turtle.circle(50)

turtle.penup()
turtle.goto(-50,-100)
turtle.pendown()
turtle.color("green")
turtle.circle(50)

###############################
turtle.penup()
turtle.goto(-50,0)
turtle.pendown()
turtle.color("blue")
turtle.circle(25)

turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.color("green")
turtle.circle(25)

turtle.penup()
turtle.goto(50,0)
turtle.pendown()
turtle.color("black")
turtle.circle(25)

turtle.penup()
turtle.goto(25,-50)
turtle.pendown()
turtle.color("green")
turtle.circle(25)

turtle.penup()
turtle.goto(-25,-50)
turtle.pendown()
turtle.color("green")
turtle.circle(25)
turtle.done()
